### PR TITLE
Make possible to use not LuceneIndexes in Umbraco.

### PR DESCRIPTION
**Pull request by bielu**
Hi Shannon, 
As I am almost finished with my ElasticSearch provider I notice to make possible to override basic indexes in Umbraco, I was getting 500 errors, because it was impossible to cast my index to LuceneIndex, here are I am attaching my changes to Lucene and as soon they will be approved I will prepare PR for Umbraco. :) 
**Description of Changes:**
Make possible to use IIndex instead of Lucene index in ExamineManagementController, moving CommitCount to be abstract.
If you have any comments I happy to prepare additional changes.

### CODE REVIEW

**Comment by Shazwazza** [comment]
Hi,

There of course shouldn't be any casting in Umbraco to LuceneIndex - but now that you point this out it looks like this is still the case for `ExamineManagementController.Indexer_IndexOperationComplete` ... is that where you are looking? This must be left over from v7 and overlooked. In this case, the index should be casted to `IIndex` and the `CommitCount` simply shouldn't be used.

I'm unsure why the other changes are made in this PR? `CommitCount` is not really used for anything anymore - also left over from 0.9 but potentially could be handy.

**Comment by bielu** [comment]
Hi @Shazwazza,
Yes, I was exactly looking at that ExamineManagementController.Indexer_IndexOperationComplete, because actually on indexing different indexes than Lucene ones. :) 
I was just thinking CommitCount is quite helpful information, about how much of documents was tried to index/remove, but if you are thinking it should be used at all, we could just ignore that PR and remove using of CommitCount in v8 :).

**Comment by Shazwazza** [comment]
It might be helpful but i think contextually it only makes sense for things that 'commit' documents, not all indexers may do that. 

Yep i think we just remove the usage of CommitCount in v8 and that should be good, it seemed only used in logs anyways ;)

**Comment by bielu** [comment]
Yep, Thanks. Good point about not all indexers will do that.

**Pull request closed without merging**
