### PR TITLE
WIP: Upgrade to lucene 4.8

### PR DESCRIPTION
**Pull request by bielu**
@Shazwazza I think it is a good idea to start the migration of Lucene from 3 to 4.8
I started a few things it requires a lot of work still from me.
I will update you on the progress of that, now I am working to upgrade tests and azure directory projects

### CODE REVIEW

**Comment by bielu** [comment]
Breaking changes:

1. Fuzy Queries: as Lucene 4.8 by default not use float description of fuzyness but int following query will return the different result:
```    var filter = criteria.Field("Content", "think".Fuzzy(0.1F));```
3.0.3 result:
`+Content:think~0.1`
4.8 result:
`+Content:think~2`

**Comment by bielu** [comment]
@Shazwazza I have a small issue with that test:
Index_Read_And_Write_Ensure_No_Errors_In_Async
as for 10 runs, it is failing around 3 times and 7 passes, do you have maybe idea what is the reason behind that?

**Comment by Shazwazza** [comment]
Interesting stuff :) Not sure when I'll have time to fully go through all of this but a glance at the changes looks fine. With Lucene.Net 4.8+ I was hoping to start using the SearchManager and NrtManager built in which manages the open searchers and NRT (near real time) stuff for you, whereas currently we are managing all of this ourselves within Examine. 

It's not hugely important at this stage, better to get things working first and then can play around with this stuff ... that is, if we even want it. Could be that Examine's handling of open searchers, etc... all works (a lot of it is inspired by these things)

Not sure about `Index_Read_And_Write_Ensure_No_Errors_In_Async` off the top of my head. I assume you don't have problems with this with the Examine 1.0 codebase with lucene 3.x?

**Comment by bielu** [comment]
@Shazwazza actually it happens but it was much less repeatable about less than 1% of runs :)

**Comment by DurtyFree** [comment]
Great library, would love to see support for Lucene 4.8 !

**Comment by bielu** [comment]
@Shazwazza resolved conflicts will look into failing Unit tests soon :)

**Comment by bielu** [comment]
Hi @Shazwazza 
I went through all failing unit tests:
2 are that which had to be discussed with you.
Last one Custom_Lucene_Query_With_Raw I am still analysing, even if the result of both queries is exactly same, why it is generating a different query.

**Comment by bielu** [comment]
@Shazwazza should I change the base of PR to net core branch and move that against the Examine.Lucene?

**Comment by Shazwazza** [comment]
@bielu yep that would be best! thanks :)

**Comment by bielu** [comment]
@Shazwazza I moved PR and make more changes when I will have little more time later today :)

**Comment by bielu** [comment]
I will have to still make a change to Azure Provider to make sure everything is working as should :)

**Comment by bielu** [comment]
@Shazwazza I am going through AzureDirectory and here I have an issue:
- Lucene.net doesn't have any more Directory.FileModified(fileName);
but also I found by an incident that repo:
https://github.com/azure-contrib/AzureDirectory
they using really similar code as Examine.AzureDirectory, and they solve the issue, but I am not sure about how they have done that... as they are storing path of the index and checking the last modification date of file
Do you have any better ideas?

**Comment by Shazwazza** [comment]
@bielu yeah the original AzureDirectory was flawed and didn't work with lucene 2.x which is why i adopted and re-wrote it and sent them a PR or two. We still have our own implementation which has a bunch of fixes than the original. I haven't looked at this code for a *very* long time so off the top of my head I'm unsure. It also might come down to how often this check needs to happen.... if it's super constant then prob not ideal to iterate over the files... however there's a good chance that was what Lucene's Directory.FileModified method was doing anyways, might be worth looking at that since if that's the case then we'd be no worse off than before.

**Comment by bielu** [comment]
@Shazwazza will look into Lucene's Directory.FileModified tomorrow

**Comment by bielu** [comment]
@Shazwazza ok here is code which Lucene is doing:
`
      return (long) new FileInfo(Path.Combine(this.internalDirectory.FullName, name)).LastWriteTime.ToUniversalTime().Subtract(new DateTime(1970, 1, 1, 0, 0, 0)).TotalMilliseconds;`

the only issue which I am seeing here to implement that in Examine is this.internalDirectory.FullName, as we don't have access to the internals of Lucene.Net and we are not aware what is a type of cache directory :/

**Comment by bielu** [comment]
@Shazwazza I updated PR and will work at some point to fix AzureDirectory probably will do same as AzureDirectory as from my check it should be big performance deal here.

**Comment by bielu** [comment]
Hi @Shazwazza, 
I made some change and now AzureDirectory works for indexing but reading cause 
checksum failed (hardware problem?) : expected=0 actual=d8185269 (resource=BufferedChecksumIndexInput(SimpleFSIndexInput(path="\ExamineIndexes\5b23f158a34847f22d9400627dda2734\3b16a85115e6788a97c3b18ebaa07564\_3.cfe")))
Do you have maybe idea how to fix that, as I run out of ideas and knowledge here :) 
btw Here is screenshot from Blob storage:
image

and from temp folder:

image

**Comment by Shazwazza** [comment]
Damn, nope i haven't seen that error before :( 
I still never managed to release the azure directory provider for compatibility with lucene 3.0.3 and umb 8 yet 😱 prob should do that soon too. Thanks again for all this help! I will review this soon - plus we have a task for this internally for the netcore dev of umbraco to make sure this is all done so it's great you've already made that happen 🎉 🎉

**Comment by bielu** [comment]
Hi Shannon did you manage to look over that maybe? 
or Soon is Microsoft Soonish? 😂😂😂

**Comment by Shazwazza** [comment]
Still starred in my inbox and not forgotten 😊 I suppose this is Microsoft Soon :P but it will definitely be "Soon"!

**Comment by DurtyFree** [comment]
So this is open since late 2019, can we expect a merge this year? 😁

**Comment by Shazwazza** [comment]
@DurtyFree yes you can.

Progress on this will commence soon alongside Umbraco netcore's version when updated to use this which is scheduled to be very soon.

**Comment by bielu** [comment]
@Shazwazza we should also address there slowly change to be .net standard not have dependency on system.web on implementation of lucene, but also probably 1000 another small bits :D

**Comment by Shazwazza** [comment]
@bielu the 2.x version will be netstandard with lucenenet 4.8. I don't really think it's worth worrying too much about the current 1.x version since lucene 3.x is not netstandard and never will be.

**Comment by bielu** [comment]
@Shazwazza I was commenting on 4.8 code, which I include there :)

**Comment by Shazwazza** [comment]
RE: the breaking changes comment above. After looking into it this is the result:

> Fuzy Queries: as Lucene 4.8 by default not use float description of fuzyness but int following query will return the different result:
> var filter = criteria.Field("Content", "think".Fuzzy(0.1F));
> 3.0.3 result:
> +Content:think~0.1
> 4.8 result:
> +Content:think~2

This is sort of correct, the input is still a float but it gets converted to an int representing 0 to MAX DISTANCE. We don't need to worry about that. The reason the test failed is because we were comparing words "thought" and "think" and other derivatives. These english stems are no longer included in the StandardAnalyzer. Instead are in the EnglishAnalyzer. 

> The standard analyzer doesn't remove any more special characters like "_", "-" etc, in 4.8 that is done by Simple Analyzer

Yes. The Standard Analyzer no longer uses the apostrophe filter. You can create your own Standard analyzer that does if you wanted. Turns out apostrophes are important in some langs.

> Proximity was counted incorrectly in Lucene 3.0.3 for following example:
> var filter = criteria.Field("metaKeywords", "Warren creative".Proximity(5));
> Correct result for test Examiness_Proximity is 2, not 3, as Lucene 3.0.3 wasn't aware of directions

This was actually due to the usage of apostrophe's with the standard analyzer as per above, not about direction. These tests are passing now.

Thanks!

**Pull request merged**
