### PR TITLE
Update/4.8.0 beta00016

### PR DESCRIPTION
**Pull request by bielu**
HI @Shazwazza,
there is small update of lucene, I resolved all issues related to breaking changes between betas :)

### CODE REVIEW

**Comment by Shazwazza** [comment]
Awesome stuff, i'll get to this shortly!

**Comment by Shazwazza** [comment]
Hi @bergmania - there are subtle breaking changes between beta versions of Lucene. Considering Umbraco 10 is supposed to be out 2nd quarter, IMO this should wait for then (with the latest Lucene beta), bump Examine to 3.0 with a .NET 6 target.  What do you think?

**Comment by NightOwl888** [comment]
IMO you should also fix the obsolete build warnings on this. These APIs will be removed in future releases of Lucene.NET.

Also, not sure why you are not getting an obsolete warning for [this line](https://github.com/Shazwazza/Examine/pull/270/files#diff-3f32f181fa473bae0175ced179aa31dc931e9f23b078f88fa48d08eeae531908R115), but the Spatial4n constant names have also been renamed to be PascalCase.

**Comment by bergmania** [comment]
> Hi @bergmania - there are subtle breaking changes between beta versions of Lucene. Considering Umbraco 10 is supposed to be out 2nd quarter, IMO this should wait for then (with the latest Lucene beta), bump Examine to 3.0 with a .NET 6 target. What do you think?

Hi @Shazwazza ..

The target for Umbraco 10 is mid june, with RC in the beginning of may.  Do you think that we work out, with a new examine release before may?

**Comment by Shazwazza** [comment]
Hi @bergmania 

> Do you think that we work out, with a new examine release before may?

Yes for sure, there isn't a whole lot to do and this PR probably covers most. I'll have to check with whatever latest Lucene version is available then and there may be other minor changes. 

I can start creating a new major version branch for this and go from there.

**Comment by bergmania** [comment]
> Hi @bergmania
> 
> > Do you think that we work out, with a new examine release before may?
> 
> Yes for sure, there isn't a whole lot to do and this PR probably covers most. I'll have to check with whatever latest Lucene version is available then and there may be other minor changes.
> 
> I can start creating a new major version branch for this and go from there.

Hi @Shazwazza, any updates on a new major? and potential release date?

**Comment by Shazwazza** [comment]
@bergmania I've created the new branch, merged this in, fixed up some obsolete warnings and removed some dead code (which I don't believe is used by Umbraco). There's an issue though, with the latest version of Lucene 4.8.0-beta00016 compared to 14, the unit tests in this project run extremely slow so something must be a little off with this version of Lucene. I'd have to run some analysis to see where the bottlenecks are.

You can see the tests here took 2 min 30 second: https://github.com/Shazwazza/Examine/runs/6121112106?check_suite_focus=true

But the previous version on dev branch took 52 seconds https://github.com/Shazwazza/Examine/runs/6120974440?check_suite_focus=true

Not sure if @NightOwl888 has any initial thoughts on why this could be?

**Comment by Shazwazza** [comment]
@bergmania you can find the 3.0 alpha artifacts here https://github.com/Shazwazza/Examine/actions/runs/2204993703 for now

**Pull request merged**
