### PR TITLE
Make Examine .NET Standard Package

### PR DESCRIPTION
**Pull request by bielu**
@Shazwazza as we spoke I started working on Standard Package
here will much more work than on migrating to 4.8 :) 
Requirements: 
First merge: https://github.com/Shazwazza/Examine/pull/140#issue-332544991
Things to do:

- [x] Switch project to netstandard
- [ ] Migrate TypeHelper
- [ ] Migrate IOHelper
- [ ] Migrate SyncMutexManager
- [ ] Migrate TempEnvDirectoryFactory
- [ ] Migrate ExamineManager
- [ ] Migrate AzureDirectoryFactory
- [ ] Restore Custom targets to project
- [ ] Restore Git tasks

### CODE REVIEW

**Comment by Shazwazza** [comment]
I've done some of the changes but have some comments:

* I think it's best we look at using the built in Lucene replicator for syncing anything, see https://lucenenet.apache.org/docs/4.8.0-beta00014/api/replicator/Lucene.Net.Replicator.html. This would simplify all of the code, no need for custom directories or syncing. It would just replicate from the master (possibly on a timer). When enabled we make sure the main index is created with a `SnapshotDeletionPolicy`. Side note, this was also a requirement in lucene 2 and 3 if trying to use the older way to 'backup' an index. I'm wondering if by using SnapshotDeletionPolicy even in the current Examine, that this solves the problem of merge policies with syncing?
* Some others above are no longer relevant
* I'll be cleaning up a ton more and refactoring bits (i.e. using [SearcherManager](https://lucenenet.apache.org/docs/4.8.0-beta00014/api/core/Lucene.Net.Search.SearcherManager.html), removing statics, better DI handling

Just wanted to keep you posted. I'll be creating some other tasks for a few of these too.

**Comment by Shazwazza** [comment]
Ooops forgot about the other thing: Mutex

I'm not sure why this is currently using named system-wide mutexes to manage the syncing. That code was borrowed from the original Azure Directory project. A system wide named mutex is expensive and there should be no need for that. Also I very much doubt that even works as expected on Azure since named Semaphores don't work as expected there and end up just working like non-named syncs. I've changed how it works in the netcore branch, i think we should prob do the same in the current branch too.

**Comment by bielu** [comment]
@Shazwazza also we should look into https://github.com/Shazwazza/Examine/issues/157 soon :)

**Comment by Shazwazza** [comment]
Yep that will be part of this work that I'm doing

**Pull request merged**
